ALTER TABLE "merchant_channels" ADD COLUMN "whatsapp_business_account_id" text;--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD COLUMN "whatsapp_phone_number_id" text;--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD COLUMN "whatsapp_display_phone_number" text;--> statement-breakpoint
CREATE UNIQUE INDEX "merchant_channels_whatsapp_phone_number_unique" ON "merchant_channels" USING btree ("whatsapp_phone_number_id") WHERE "whatsapp_phone_number_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "merchant_channels_whatsapp_waba_idx" ON "merchant_channels" USING btree ("whatsapp_business_account_id") WHERE "whatsapp_business_account_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_identity_pair_check" CHECK (("whatsapp_business_account_id" IS NULL AND "whatsapp_phone_number_id" IS NULL AND "whatsapp_display_phone_number" IS NULL) OR ("whatsapp_business_account_id" IS NOT NULL AND "whatsapp_phone_number_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_identity_format_check" CHECK (("whatsapp_business_account_id" IS NULL OR "whatsapp_business_account_id" ~ '^[0-9]{1,40}$') AND ("whatsapp_phone_number_id" IS NULL OR "whatsapp_phone_number_id" ~ '^[0-9]{1,40}$'));--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_identity_scope_check" CHECK ("platform" = 'whatsapp' OR ("whatsapp_business_account_id" IS NULL AND "whatsapp_phone_number_id" IS NULL AND "whatsapp_display_phone_number" IS NULL));--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_channel_shape_check" CHECK ("platform" <> 'whatsapp' OR ("external_account_id" IS NULL AND "external_account_name" IS NULL AND "page_id" IS NULL AND "page_name" IS NULL AND "instagram_account_id" IS NULL AND "instagram_username" IS NULL));--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_dormant_only_check" CHECK ("platform" <> 'whatsapp' OR ("status" = 'pending' AND "credential_ciphertext" IS NULL AND "credential_nonce" IS NULL AND "credential_auth_tag" IS NULL AND "credential_key_id" IS NULL AND "credential_algorithm" IS NULL AND "credential_expires_at" IS NULL AND "webhook_subscribed_at" IS NULL AND "last_webhook_at" IS NULL AND "connected_at" IS NULL));