ALTER TABLE "merchant_channels" ADD COLUMN "whatsapp_business_account_id" text;--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD COLUMN "whatsapp_phone_number_id" text;--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD COLUMN "whatsapp_display_phone_number" text;--> statement-breakpoint
CREATE UNIQUE INDEX "merchant_channels_whatsapp_phone_number_unique" ON "merchant_channels" USING btree ("whatsapp_phone_number_id") WHERE "merchant_channels"."whatsapp_phone_number_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "merchant_channels_whatsapp_waba_idx" ON "merchant_channels" USING btree ("whatsapp_business_account_id") WHERE "merchant_channels"."whatsapp_business_account_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_identity_pair_check" CHECK (("merchant_channels"."whatsapp_business_account_id" IS NULL AND "merchant_channels"."whatsapp_phone_number_id" IS NULL AND "merchant_channels"."whatsapp_display_phone_number" IS NULL) OR ("merchant_channels"."whatsapp_business_account_id" IS NOT NULL AND "merchant_channels"."whatsapp_phone_number_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_identity_format_check" CHECK (("merchant_channels"."whatsapp_business_account_id" IS NULL OR "merchant_channels"."whatsapp_business_account_id" ~ '^[0-9]{1,40}$') AND ("merchant_channels"."whatsapp_phone_number_id" IS NULL OR "merchant_channels"."whatsapp_phone_number_id" ~ '^[0-9]{1,40}$'));--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_identity_scope_check" CHECK ("merchant_channels"."platform" = 'whatsapp' OR ("merchant_channels"."whatsapp_business_account_id" IS NULL AND "merchant_channels"."whatsapp_phone_number_id" IS NULL AND "merchant_channels"."whatsapp_display_phone_number" IS NULL));--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_channel_shape_check" CHECK ("merchant_channels"."platform" <> 'whatsapp' OR ("merchant_channels"."external_account_id" IS NULL AND "merchant_channels"."external_account_name" IS NULL AND "merchant_channels"."page_id" IS NULL AND "merchant_channels"."page_name" IS NULL AND "merchant_channels"."instagram_account_id" IS NULL AND "merchant_channels"."instagram_username" IS NULL));--> statement-breakpoint
ALTER TABLE "merchant_channels" ADD CONSTRAINT "merchant_channels_whatsapp_dormant_only_check" CHECK ("merchant_channels"."platform" <> 'whatsapp' OR ("merchant_channels"."status" = 'pending' AND "merchant_channels"."credential_ciphertext" IS NULL AND "merchant_channels"."credential_nonce" IS NULL AND "merchant_channels"."credential_auth_tag" IS NULL AND "merchant_channels"."credential_key_id" IS NULL AND "merchant_channels"."credential_algorithm" IS NULL AND "merchant_channels"."credential_expires_at" IS NULL AND "merchant_channels"."webhook_subscribed_at" IS NULL AND "merchant_channels"."last_webhook_at" IS NULL AND "merchant_channels"."connected_at" IS NULL));