ALTER TABLE "catalog_idempotency_keys" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "catalog_identifiers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "catalog_image_references" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "catalog_variant_options" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "inventory_mutations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_variants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "channel_inbound_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "outbound_deliveries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "reply_refunds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "reply_reservations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "merchant_channels" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "commerce_promotions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "conversations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "merchant_location_delivery_areas" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "reply_ledger" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "subscription_reply_batches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "saas_billing_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "saas_billing_orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "saas_billing_refunds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "saas_entitlement_applications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "order_payment_decisions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "order_payment_provider_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "order_terminal_decision_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "knowledge_audit_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "knowledge_embeddings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "learned_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "saved_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "training_requests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "background_job_payloads" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "background_jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "merchant_delivery_area_rates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "merchant_settings" ENABLE ROW LEVEL SECURITY;
