import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(testDirectory, "../..");

function read(relativePath) {
  return fs.readFileSync(path.join(repositoryRoot, relativePath), "utf8");
}

test("report surfaces expose custom date range, Excel export, print and charts", () => {
  const cashier = read("artifacts/fawri/src/pages/dashboard/CashierCentralReportsPage.tsx");
  const reports = read("artifacts/fawri/src/pages/dashboard/ReportsPage.tsx");
  const toolbar = read("artifacts/fawri/src/components/reports/ReportToolbar.tsx");
  const printCss = read("artifacts/fawri/src/pages/dashboard/reports-print.css");
  const workbook = read("artifacts/fawri/src/lib/reportWorkbook.ts");

  assert.match(toolbar, /Dialog/);
  assert.match(toolbar, /DialogContent/);
  assert.match(toolbar, /max-h-\[calc\(100dvh-2rem\)\]/);
  assert.match(toolbar, /overflow-y-auto/);
  assert.match(toolbar, /Calendar/);
  assert.match(toolbar, /mode="range"/);
  assert.match(toolbar, /min=\{1\}/);
  assert.match(toolbar, /numberOfMonths=\{desktopCalendar \? 2 : 1\}/);
  assert.match(toolbar, /displayDateDayFirst/);
  assert.match(toolbar, /\$\{day\}\/\$\{month\}\/\$\{year\}/);
  assert.match(toolbar, /Quick ranges/);
  assert.match(toolbar, /Choose the start date, then the end date on the calendar\./);
  assert.match(toolbar, /Cancel/);
  assert.match(toolbar, /Apply/);
  assert.match(toolbar, /draftRange\.to \?\? draftRange\.from/);
  assert.doesNotMatch(toolbar, /type="date"/);
  assert.match(toolbar, /Download Excel/);
  assert.match(toolbar, /Print \/ Save PDF/);
  assert.match(toolbar, /localDateEndExclusive/);
  assert.match(toolbar, /params\.set\('to'/);

  assert.match(cashier, /top_profitable_products/);
  assert.match(cashier, /ResponsiveContainer/);
  assert.match(cashier, /PieChart/);
  assert.match(cashier, /<Pie/);
  assert.match(cashier, /<Cell/);
  assert.match(cashier, /REPORT_CHART_COLORS/);
  assert.doesNotMatch(cashier, /<BarChart/);
  assert.match(cashier, /arabicVisualDateFromIso/);
  assert.match(cashier, /report-print-period-row/);
  assert.match(cashier, /report-print-metric-value/);
  assert.match(cashier, /report-summary-metrics report-print-metrics/);
  assert.match(cashier, /report-summary-metric rounded/);
  assert.match(printCss, /@media screen and \(min-width: 1024px\)/);
  assert.match(printCss, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.doesNotMatch(printCss, /repeat\(auto-fit/);
  assert.match(toolbar, /function ArabicRangeDetail/);
  assert.match(toolbar, /dir=\{lang === 'ar' \? 'ltr' : undefined\} className="report-date-actions flex shrink-0 items-center justify-end/);
  assert.match(toolbar, /<bdi dir="ltr">/);
  assert.match(toolbar, /index === 0 \? 'من' : 'إلى'/);
  assert.match(cashier, /report-print-chart-canvas/);
  assert.match(cashier, /report-print-chart-dot/);
  assert.match(cashier, /DonutProductChart/);
  assert.match(cashier, /chartPercentText/);
  assert.match(cashier, /chartRankLabel/);
  assert.match(cashier, /report-print-chart-panel/);
  assert.match(cashier, /report-print-cashier-chart-card/);
  assert.match(cashier, /inline-flex items-center gap-1\.5 font-semibold/);
  assert.match(cashier, /report-print-chart-legend/);
  assert.match(cashier, /report-print-chart-percent/);
  assert.doesNotMatch(cashier, /report-print-donut-label/);
  assert.match(cashier, /formatReportMoneyMinor/);
  assert.match(cashier, /operationCountUnit/);
  assert.match(cashier, /report-print-operation-kind/);
  assert.match(cashier, /downloadWorkbook/);
  assert.match(cashier, /labels\.currency/);
  assert.match(cashier, /labels\.period/);
  assert.match(cashier, /formatDayFirstDateTime/);
  assert.match(cashier, /columnWidths/);
  assert.match(cashier, /autoFilter: true/);
  assert.match(cashier, /item\.sale_id/);
  assert.match(cashier, /item\.shift_id/);
  assert.match(cashier, /labels\.location,\s*labels\.station,\s*labels\.amount,\s*labels\.currency,\s*labels\.saleReference,\s*labels\.shift/);
  assert.match(cashier, /metric: 'المؤشر'/);
  assert.match(cashier, /value: 'القيمة'/);
  assert.match(cashier, /\[labels\.currency, labels\.metric, labels\.value, labels\.profitStatus\]/);
  assert.match(cashier, /columnWidths: \[16, 34, 22, 22\]/);
  assert.match(cashier, /cashierExportSheetNames/);
  assert.match(cashier, /summary: 'الملخص'/);
  assert.match(cashier, /topSelling: 'الأكثر مبيعًا'/);
  assert.match(cashier, /topProfitable: 'الأكثر ربحية'/);
  assert.match(cashier, /operations: 'العمليات'/);
  assert.match(cashier, /mergeRanges:/);
  assert.match(cashier, /operationNoticeRows/);
  assert.match(cashier, /operationNoticeRows\.map\(row => \(\{ startRow: row, startColumn: 0, endRow: row, endColumn: 8 \}\)\)/);
  assert.match(cashier, /startRow: 1, startColumn: 1, endRow: 1, endColumn: 3/);
  assert.match(cashier, /startRow: 3, startColumn: 0, endRow: 3, endColumn: 3/);
  assert.match(cashier, /rowHeights: \[24, 22, 22, 22, 10, 24\]/);
  assert.match(cashier, /columnWidths: \[26, 20, 14, 18, 20, 16, 12, 44, 46\]/);
  assert.match(cashier, /ltrDataColumns: \[0, 7, 8\]/);
  assert.match(cashier, /\{ row: 1, column: 1 \}/);
  assert.match(cashier, /\{ row: 2, column: 1 \}/);
  assert.match(cashier, /currency\.profit_status === 'unavailable' \? ''/);
  assert.match(cashier, /window\.print\(\)/);
  assert.match(cashier, /report-print-only/);
  assert.match(cashier, /report-print-metrics/);
  assert.match(cashier, /report-print-currency-section/);
  assert.match(cashier, /report-print-two-column/);
  assert.match(cashier, /report-print-three-column/);
  assert.match(cashier, /report-print-operation-page/);
  assert.match(cashier, /report-print-operation-details/);
  assert.match(cashier, /report-print-operation-table/);
  assert.match(cashier, /report-print-operation-grid/);
  assert.match(cashier, /report-print-operation-head/);
  assert.match(cashier, /report-print-operation-cell/);
  assert.match(cashier, /report-print-operation-date/);
  assert.match(cashier, /const datePart = formatDayFirst\(instant\)/);
  assert.match(cashier, /report-print-operation-tech/);
  assert.match(cashier, /partialProfitShort/);
  assert.match(cashier, /historicalActivityNote/);
  assert.match(cashier, /hasHistoricalActivityGap/);
  assert.match(cashier, /report-print-activity-coverage/);
  assert.match(cashier, /shortShiftReference/);
  assert.match(cashier, /localizedLegacyName/);
  assert.match(cashier, /unattributed legacy location/);
  assert.match(cashier, /unattributed legacy cashier/);
  assert.match(cashier, /unattributed legacy station/);
  assert.match(cashier, /report-print-group-summary-block/);
  assert.match(cashier, /report-print-group-card/);
  assert.match(cashier, /report-print-group-stats/);
  assert.match(cashier, /report-print-group-stat-card/);
  assert.match(cashier, /report-print-group-stat-value/);
  assert.match(cashier, /report-print-activity-card/);
  assert.match(cashier, /report-print-activity-stats/);
  assert.match(cashier, /report-print-activity-stat-card/);
  assert.match(cashier, /report-print-activity-stat-value/);
  assert.match(cashier, /report-print-footer-note/);
  assert.match(cashier, /xl:overflow-x-visible/);
  assert.match(cashier, /xl:min-w-0/);

  assert.match(reports, /reportRangeQuery/);
  assert.match(reports, /downloadWorkbook/);
  assert.match(reports, /profitabilityUnavailable/);
  assert.match(reports, /reports-print\.css/);
  assert.match(reports, /ArabicOnlineReportsContent/);
  assert.match(reports, /lang === 'ar' \? \(/);
  assert.match(reports, /ONLINE_REPORT_CHART_COLORS/);
  assert.match(reports, /<PieChart>/);
  assert.match(reports, /<Pie/);
  assert.match(reports, /<Cell/);
  assert.match(reports, /arabicOnlinePercent/);
  assert.match(reports, /formatArabicGroupedInteger/);
  assert.match(reports, /formatArabicIqd/);
  assert.match(reports, /report-print-online-metrics/);
  assert.match(reports, /report-print-online-groups/);
  assert.match(reports, /report-print-online-group-section/);
  assert.match(reports, /report-print-online-group-card/);
  assert.match(reports, /report-print-online-products/);
  assert.match(reports, /report-print-chart-legend/);
  assert.match(reports, /report-print-chart-percent/);
  assert.match(reports, /المصدر: سجل الطلبات الإلكترونية الموثوق على السيرفر/);
  assert.match(printCss, /@media print/);
  assert.match(printCss, /report-no-print/);
  assert.match(printCss, /report-print-only/);
  assert.match(printCss, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(printCss, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(printCss, /report-print-operation-page/);
  assert.match(printCss, /break-before: page/);
  assert.match(printCss, /page-break-before: always/);
  assert.match(printCss, /display: table-header-group/);
  assert.match(printCss, /report-print-operation-table/);
  assert.match(printCss, /scrollbar-width: none/);
  assert.match(printCss, /::-webkit-scrollbar/);
  assert.match(printCss, /display: none/);
  assert.match(printCss, /report-print-operation-details tbody tr/);
  assert.match(printCss, /height: 40mm/);
  assert.match(printCss, /max-width: 72mm/);
  assert.match(printCss, /report-print-chart-panel/);
  assert.match(printCss, /report-print-chart-card/);
  assert.match(printCss, /report-print-cashier-chart-card/);
  assert.match(printCss, /grid-template-columns: 50mm minmax\(0, 1fr\)/);
  assert.match(printCss, /grid-template-areas:/);
  assert.match(printCss, /height: 50mm/);
  assert.match(printCss, /report-print-currency-section/);
  assert.match(printCss, /\.report-print-currency-section\s*\{[^}]*break-inside: auto !important;[^}]*page-break-inside: auto !important;/);
  assert.match(printCss, /report-print-profit-status/);
  assert.match(printCss, /report-print-activity-coverage/);
  assert.match(printCss, /box-sizing: border-box/);
  assert.match(printCss, /report-print-chart-legend-row/);
  assert.doesNotMatch(printCss, /report-print-donut-label/);
  assert.match(printCss, /report-print-operation-kind/);
  assert.match(printCss, /background: transparent/);
  assert.match(printCss, /font-size: 7\.4pt/);
  assert.match(printCss, /page-break-inside: avoid/);
  assert.match(printCss, /report-print-metric-value/);
  assert.match(printCss, /report-print-period-row/);
  assert.match(printCss, /report-print-chart-canvas/);
  assert.match(printCss, /print-color-adjust: exact/);
  assert.match(printCss, /font-size: 10\.5pt/);
  assert.match(printCss, /font-size: 7\.8pt/);
  assert.match(printCss, /font-size: 7\.6pt/);
  assert.match(printCss, /border-inline-end/);
  assert.match(printCss, /vertical-align: middle/);
  assert.match(printCss, /tbody tr:nth-child\(even\)/);
  assert.match(printCss, /report-print-group-summary-block/);
  assert.match(printCss, /report-print-group-stat-value/);
  const screenCss = printCss.split('@media print')[0];
  assert.match(screenCss, /\.report-print-group-stat-card\s*\{[^}]*align-items: center;[^}]*text-align: center;/);
  assert.match(screenCss, /\.report-print-group-stat-value\s*\{[^}]*justify-content: center;/);
  assert.match(screenCss, /\.report-print-group-stat-value > \*\s*\{[^}]*align-items: center;/);
  assert.match(printCss, /report-print-activity-stat-value/);
  assert.match(printCss, /report-print-group-card/);
  assert.match(printCss, /report-print-activity-card/);
  assert.match(printCss, /report-print-footer-note/);
  assert.match(printCss, /report-print-online-metric/);
  assert.match(printCss, /report-print-online-note/);
  assert.match(printCss, /report-print-online-group-section/);
  assert.match(printCss, /report-print-online-group-card/);
  assert.match(printCss, /report-print-online-products/);
  assert.match(printCss, /report-print-online-profit-note/);
  assert.match(printCss, /report-print-online-products \.report-print-chart-canvas/);
  assert.match(printCss, /height: 46mm/);
  assert.match(printCss, /break-after: avoid/);
  assert.match(cashier, /rtlText: lang !== 'en'/);
  assert.match(workbook, /stylesXml/);
  assert.match(workbook, /ltrCells/);
  assert.match(workbook, /ltrDataColumns/);
  assert.match(workbook, /readingOrder="1"/);
  assert.match(workbook, /rightToLeft="1"/);
  assert.match(workbook, /<borders count="2">/);
  assert.match(workbook, /style="thin"/);
  assert.match(workbook, /numFmtId="3"/);
  assert.match(workbook, /mergeRanges/);
  assert.match(workbook, /rowHeights/);
  assert.match(workbook, /<autoFilter ref=/);
  assert.match(workbook, /fileType: 'zip'/);
  assert.match(workbook, /new ArrayBuffer\(bytes\.byteLength\)/);
  assert.match(workbook, /new Uint8Array\(arrayBuffer\)\.set\(bytes\)/);
  assert.match(workbook, /application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet/);
});

test("cashier profitability requires complete historical cost evidence", () => {
  const service = read(
    "artifacts/api-server/src/services/postgresCashierCentralReportAuthority.ts",
  );

  assert.match(service, /cost_unknown_affected_units/);
  assert.match(service, /profit_status/);
  assert.match(service, /top_profitable_products/);
  assert.match(service, /product\.profit_status === "available"/);
  assert.match(service, /gross_profit_minor/);
  assert.doesNotMatch(service, /unit_cost_minor \?\? 0/);
});


test("Arabic report calendar has localized, spaced range controls without changing date boundaries", () => {
  const toolbar = read("artifacts/fawri/src/components/reports/ReportToolbar.tsx");
  const css = read("artifacts/fawri/src/components/reports/report-calendar.css");
  assert.match(toolbar, /lang === 'ar' \? DayPicker : Calendar/);
  assert.match(toolbar, /locale=\{lang === 'ar' \? ar : undefined\}/);
  assert.match(toolbar, /numerals=\{lang === 'ar' \? 'arab' : undefined\}/);
  assert.match(toolbar, /labelNext: \(\) => 'الشهر التالي'/);
  assert.match(toolbar, /labelPrevious: \(\) => 'الشهر السابق'/);
  assert.match(css, /\.report-ar-calendar \.rdp-month_grid/);
  assert.match(css, /table-layout: fixed/);
  assert.match(css, /min-height: 2\.5rem/);
  assert.match(css, /\.rdp-range_start \.rdp-day_button/);
  assert.match(css, /\.rdp-range_end \.rdp-day_button/);
  assert.match(toolbar, /params\.set\('from', localDateStart\(custom\.from\)\.toISOString\(\)\)/);
  assert.match(toolbar, /params\.set\('to', localDateEndExclusive\(custom\.to\)\.toISOString\(\)\)/);
});
