import type { Lang } from '@/lib/types';

export const CASHIER_POS_ENHANCEMENT_COPY = {
  ar: {
    checkout: 'الدفع',
    checkoutTitle: 'إتمام الدفع',
    checkoutSubtitle: 'راجع الإجمالي واختر طريقة الدفع قبل تسجيل البيع.',
    closeCheckout: 'إغلاق',
    cancelCheckout: 'رجوع',
    confirmSale: 'تأكيد البيع',
    scannerReady: 'قارئ الباركود جاهز — امسح من أي مكان في شاشة البيع.',
    scannerNotFound: 'لم يتم العثور على منتج أو متغير بهذا الباركود أو SKU.',
    scannerAmbiguous: 'هذا الباركود أو SKU مرتبط بأكثر من عنصر. صححه من صفحة المنتجات قبل البيع.',
    catalogOpenFailed: 'تعذر فتح كتالوج الكاشير على هذا الجهاز. أعد فتح الكاشير أو حاول المزامنة.',
    searchFailed: 'تعذر البحث في كتالوج الكاشير. حاول مرة أخرى.',
    addDiscount: 'إضافة خصم',
    removeDiscount: 'إلغاء الخصم',
    manualDiscount: 'خصم يدوي',
    promotionDiscount: 'خصم العروض',
    discountType: 'نوع الخصم',
    discountAmount: 'مبلغ',
    discountPercent: 'نسبة %',
    discountValue: 'قيمة الخصم',
    discountReason: 'سبب الخصم',
    discountReasonCustomerRecovery: 'تعويض عميل',
    discountReasonLoyalty: 'عميل دائم / ولاء',
    discountReasonPriceMatch: 'مطابقة سعر',
    discountReasonDamagedItem: 'منتج متضرر',
    discountReasonSpecialOffer: 'عرض خاص',
    discountReasonClearance: 'تصفية مخزون',
    discountReasonOther: 'أخرى',
    discountReasonAddNote: 'إضافة ملاحظة (اختياري)',
    discountReasonNotePlaceholder: 'ملاحظة إضافية...',
    discountEmployeeLimit: 'الحد المسموح لهذا الموظف',
    discountNeedsManager: 'هذا الخصم يتجاوز حد الموظف ويتطلب موافقة مدير.',
    discountOnlineRequired: 'الخصم اليدوي يحتاج اتصالًا بالإنترنت للتحقق من صلاحية الموظف.',
    discountPolicyLoading: 'جارٍ التحقق من صلاحية الخصم...',
    discountPolicyUnavailable: 'تعذر التحقق من صلاحية الخصم الآن.',
    discountReasonRequired: 'اختر سبب الخصم قبل تأكيد البيع.',
    discountValueInvalid: 'تحقق من قيمة الخصم قبل تأكيد البيع.',
    managerApprovalTitle: 'موافقة المدير',
    managerApprovalSubtitle: 'اختر مديرًا مخولًا واطلب منه إدخال PIN للموافقة على هذا الخصم فقط.',
    managerApprovalManager: 'المدير المخول',
    managerApprovalPin: 'PIN المدير',
    managerApprovalAction: 'اعتماد الخصم',
    managerApprovalChecking: 'جارٍ التحقق...',
    managerApprovalLoading: 'جارٍ تحميل المديرين المخولين...',
    managerApprovalApproved: 'تمت موافقة المدير على هذا الخصم.',
    managerApprovalNoApprovers: 'لا يوجد مدير مخول بالموافقة على تجاوز حد الخصم.',
    managerApprovalOnlineRequired: 'موافقة المدير تحتاج اتصالًا بالإنترنت.',
    managerApprovalInvalidPin: 'PIN المدير غير صحيح.',
    managerApprovalLocked: 'تم قفل PIN مؤقتًا بعد محاولات فاشلة. حاول لاحقًا.',
    managerApprovalManagerLimitExceeded: 'هذا الخصم يتجاوز حد صلاحية المدير لهذا النوع من الخصم.',
    managerApprovalFailed: 'تعذر اعتماد الخصم. تحقق من المدير والصلاحية ثم حاول مرة أخرى.',
    finalTotal: 'الإجمالي بعد الخصم',
  },
  ku: {
    checkout: 'پارەدان',
    checkoutTitle: 'تەواوکردنی پارەدان',
    checkoutSubtitle: 'کۆی گشتی و شێوازی پارەدان بپشکنە پێش تۆمارکردنی فرۆشتن.',
    closeCheckout: 'داخستن',
    cancelCheckout: 'گەڕانەوە',
    confirmSale: 'پشتڕاستکردنەوەی فرۆشتن',
    scannerReady: 'خوێنەری بارکۆد ئامادەیە — لە هەر شوێنێکی پەڕەی فرۆشتن بارکۆد بخوێنەوە.',
    scannerNotFound: 'هیچ بەرهەم یان جۆرێک بەم بارکۆد یان SKU نەدۆزرایەوە.',
    scannerAmbiguous: 'ئەم بارکۆد یان SKU ـە بە زیاتر لە یەک دانەوە بەستراوە. پێش فرۆشتن لە پەڕەی بەرهەمەکان چاکی بکە.',
    catalogOpenFailed: 'کردنەوەی کاتەلۆگی کاشێر لەم ئامێرە سەرکەوتوو نەبوو. کاشێر دووبارە بکەرەوە یان هاوکاتکردن هەوڵ بدە.',
    searchFailed: 'گەڕان لە کاتەلۆگی کاشێر سەرکەوتوو نەبوو. دووبارە هەوڵ بدە.',
    addDiscount: 'زیادکردنی داشکاندن',
    removeDiscount: 'لابردنی داشکاندن',
    manualDiscount: 'داشکاندنی دەستی',
    promotionDiscount: 'داشکاندنی ئۆفەر',
    discountType: 'جۆری داشکاندن',
    discountAmount: 'بڕ',
    discountPercent: 'ڕێژە %',
    discountValue: 'بەهای داشکاندن',
    discountReason: 'هۆکاری داشکاندن',
    discountReasonCustomerRecovery: 'قەرەبووی کڕیار',
    discountReasonLoyalty: 'کڕیاری بەردەوام / دڵسۆزی',
    discountReasonPriceMatch: 'هاوتاکردنی نرخ',
    discountReasonDamagedItem: 'کاڵای زیان‌دیتوو',
    discountReasonSpecialOffer: 'ئۆفەری تایبەت',
    discountReasonClearance: 'پاککردنەوەی کۆگا',
    discountReasonOther: 'هی تر',
    discountReasonAddNote: 'زیادکردنی تێبینی (ئارەزوومەندانە)',
    discountReasonNotePlaceholder: 'تێبینی زیادە...',
    discountEmployeeLimit: 'سنووری ڕێگەپێدراوی ئەم کارمەندە',
    discountNeedsManager: 'ئەم داشکاندنە لە سنووری کارمەند زیاترە و پەسەندی بەڕێوەبەر پێویستە.',
    discountOnlineRequired: 'داشکاندنی دەستی پێویستی بە ئینتەرنێت هەیە بۆ پشتڕاستکردنەوەی دەسەڵات.',
    discountPolicyLoading: 'دەسەڵاتی داشکاندن پشکنرێت...',
    discountPolicyUnavailable: 'ئێستا نەتوانرا دەسەڵاتی داشکاندن پشتڕاست بکرێتەوە.',
    discountReasonRequired: 'پێش پشتڕاستکردنەوەی فرۆشتن هۆکاری داشکاندن هەڵبژێرە.',
    discountValueInvalid: 'پێش پشتڕاستکردنەوەی فرۆشتن بەهای داشکاندن بپشکنە.',
    managerApprovalTitle: 'پەسەندی بەڕێوەبەر',
    managerApprovalSubtitle: 'بەڕێوەبەرێکی دەسەڵاتدار هەڵبژێرە و با PIN ـەکەی بنووسێت بۆ پەسەندکردنی تەنها ئەم داشکاندنە.',
    managerApprovalManager: 'بەڕێوەبەری دەسەڵاتدار',
    managerApprovalPin: 'PIN ـی بەڕێوەبەر',
    managerApprovalAction: 'پەسەندکردنی داشکاندن',
    managerApprovalChecking: 'پشکنین دەکرێت...',
    managerApprovalLoading: 'بەڕێوەبەرە دەسەڵاتدارەکان بار دەکرێن...',
    managerApprovalApproved: 'بەڕێوەبەر ئەم داشکاندنەی پەسەند کرد.',
    managerApprovalNoApprovers: 'هیچ بەڕێوەبەرێکی دەسەڵاتدار بۆ تێپەڕاندنی سنووری داشکاندن نییە.',
    managerApprovalOnlineRequired: 'پەسەندی بەڕێوەبەر پێویستی بە ئینتەرنێت هەیە.',
    managerApprovalInvalidPin: 'PIN ـی بەڕێوەبەر هەڵەیە.',
    managerApprovalLocked: 'PIN دوای هەوڵی هەڵە بە کاتی داخراوە. دواتر هەوڵ بدە.',
    managerApprovalManagerLimitExceeded: 'ئەم داشکاندنە لە سنووری دەسەڵاتی ئەم بەڕێوەبەرە بۆ ئەم جۆرە داشکاندنە زیاترە.',
    managerApprovalFailed: 'پەسەندکردنی داشکاندن سەرکەوتوو نەبوو. بەڕێوەبەر و دەسەڵاتەکە بپشکنە و دووبارە هەوڵ بدە.',
    finalTotal: 'کۆی دوای داشکاندن',
  },
  en: {
    checkout: 'Pay',
    checkoutTitle: 'Complete payment',
    checkoutSubtitle: 'Review the total and choose a payment method before recording the sale.',
    closeCheckout: 'Close',
    cancelCheckout: 'Back',
    confirmSale: 'Confirm sale',
    scannerReady: 'Barcode scanner ready — scan from anywhere on the sales screen.',
    scannerNotFound: 'No product or variant was found for this barcode or SKU.',
    scannerAmbiguous: 'This barcode or SKU belongs to more than one item. Correct it on the Products page before selling.',
    catalogOpenFailed: 'The cashier catalog could not be opened on this device. Reopen the cashier or try syncing.',
    searchFailed: 'Cashier catalog search failed. Try again.',
    addDiscount: 'Add discount',
    removeDiscount: 'Remove discount',
    manualDiscount: 'Manual discount',
    promotionDiscount: 'Promotion discount',
    discountType: 'Discount type',
    discountAmount: 'Amount',
    discountPercent: 'Percent %',
    discountValue: 'Discount value',
    discountReason: 'Discount reason',
    discountReasonCustomerRecovery: 'Customer recovery',
    discountReasonLoyalty: 'Loyal customer / loyalty',
    discountReasonPriceMatch: 'Price match',
    discountReasonDamagedItem: 'Damaged item',
    discountReasonSpecialOffer: 'Special offer',
    discountReasonClearance: 'Inventory clearance',
    discountReasonOther: 'Other',
    discountReasonAddNote: 'Add note (optional)',
    discountReasonNotePlaceholder: 'Additional note...',
    discountEmployeeLimit: 'This employee’s allowed limit',
    discountNeedsManager: 'This discount exceeds the employee limit and requires manager approval.',
    discountOnlineRequired: 'Manual discounts require an internet connection to verify employee authority.',
    discountPolicyLoading: 'Checking discount authority...',
    discountPolicyUnavailable: 'Discount authority could not be verified right now.',
    discountReasonRequired: 'Choose a discount reason before confirming the sale.',
    discountValueInvalid: 'Check the discount value before confirming the sale.',
    managerApprovalTitle: 'Manager approval',
    managerApprovalSubtitle: 'Choose an authorized manager and have them enter their PIN to approve this discount only.',
    managerApprovalManager: 'Authorized manager',
    managerApprovalPin: 'Manager PIN',
    managerApprovalAction: 'Approve discount',
    managerApprovalChecking: 'Checking approval...',
    managerApprovalLoading: 'Loading authorized managers...',
    managerApprovalApproved: 'Manager approval is recorded for this discount.',
    managerApprovalNoApprovers: 'No manager is authorized to approve a discount above this employee’s limit.',
    managerApprovalOnlineRequired: 'Manager approval requires an internet connection.',
    managerApprovalInvalidPin: 'The manager PIN is incorrect.',
    managerApprovalLocked: 'The PIN is temporarily locked after failed attempts. Try again later.',
    managerApprovalManagerLimitExceeded: 'This discount exceeds this manager’s allowed limit for this discount type.',
    managerApprovalFailed: 'The discount could not be approved. Check the manager and authority, then try again.',
    finalTotal: 'Total after discount',
  },
} as const satisfies Record<Lang, Record<string, string>>;