import type { Lang } from '@/lib/types';

export type CashierCentralReportsCopy = {
  title: string; subtitle: string; back: string; today: string; seven: string; thirty: string; all: string;
  loading: string; failed: string; empty: string; netSales: string; profit: string; operations: string; units: string;
  refunds: string; average: string; voided: string; returns: string; partialProfit: string; partialProfitShort: string; unavailableProfit: string; historicalActivityNote: string;
  topProducts: string; topProfitable: string; noTop: string; noProfitable: string; revenueChart: string; unitsChart: string; profitChart: string; salesByStaff: string; salesByStation: string; salesByLocation: string; activityByStaff: string; activityByStation: string; activityByLocation: string;
  noGroupSales: string; sales: string; saleOps: string; returnOps: string; voidOps: string; totalOps: string; location: string; currency: string; period: string; profitStatus: string; metric: string; value: string;
  generated: string; source: string; operationDetails: string; operationDetailsHint: string; detailsLimited: string; employeeFilter: string; locationFilter: string; stationFilter: string;
  typeFilter: string; allEmployees: string; allLocations: string; allStations: string; allTypes: string; employee: string; station: string; shift: string;
  operationType: string; saleReference: string; dateTime: string; amount: string; noDetails: string; operationCountUnit: string; formerEmployee: string; formerStation: string; formerLocation: string;
};

export const CASHIER_CENTRAL_REPORTS_COPY: Record<Lang, CashierCentralReportsCopy> = {
  ar: {
    title: 'تقرير الكاشير المركزي', subtitle: 'المبيعات والإرجاعات والإلغاءات حسب المواقع والموظفين والمحطات من السجل المركزي الموثوق.', back: 'إدارة الكاشيرات',
    today: 'اليوم', seven: '7 أيام', thirty: '30 يوم', all: 'الكل', loading: 'جارٍ إعداد التقرير المركزي...', failed: 'تعذر تحميل تقرير الكاشير المركزي.', empty: 'لا توجد عمليات كاشير ضمن هذه الفترة.',
    netSales: 'صافي المبيعات', profit: 'الربح الإجمالي', operations: 'عمليات البيع', units: 'صافي القطع المباعة', refunds: 'قيمة الإرجاعات والإلغاءات', average: 'متوسط قيمة عملية البيع', voided: 'عمليات الإلغاء', returns: 'عمليات الإرجاع',
    partialProfit: 'الربح الظاهر جزئي لأن تكلفة بعض القطع غير مسجلة.', partialProfitShort: 'ربح جزئي', unavailableProfit: 'بيانات الربح غير متاحة لهذا النطاق. لا يفترض فوري أن التكلفة صفر.', historicalActivityNote: 'تفاصيل التنفيذ متاحة لـ {available} من أصل {total} عملية. بعض العمليات التاريخية سبقت سجل ربط الموظف والموقع والمحطة، لذلك تبقى ضمن الأرقام المالية دون اختلاق بيانات إسناد غير موجودة.', topProducts: 'الأكثر مبيعًا', topProfitable: 'الأكثر ربحية', noTop: 'لا توجد منتجات بصافي بيع موجب في هذه الفترة.', noProfitable: 'لا توجد منتجات يمكن ترتيب ربحيتها بدقة ضمن هذه الفترة؛ لا يتم افتراض تكلفة مفقودة.', revenueChart: 'رسم المبيعات حسب المنتج', unitsChart: 'القطع المباعة حسب المنتج', profitChart: 'رسم الربح حسب المنتج',
    salesByStaff: 'الأثر المالي حسب موظف البيع', salesByStation: 'الأثر المالي حسب محطة البيع', salesByLocation: 'الأثر المالي حسب الموقع', activityByStaff: 'العمليات المنفذة حسب الموظف', activityByStation: 'العمليات المنفذة حسب المحطة', activityByLocation: 'العمليات المنفذة حسب الموقع', noGroupSales: 'لا يوجد أثر مالي ضمن هذه الفترة.',
    sales: 'عمليات بيع', saleOps: 'بيع', returnOps: 'إرجاع', voidOps: 'إلغاء', totalOps: 'الإجمالي', location: 'الموقع', currency: 'العملة', period: 'الفترة', profitStatus: 'حالة الربح', metric: 'المؤشر', value: 'القيمة', generated: 'آخر تحديث', source: 'المصدر: سجل الكاشير المركزي الموثوق على السيرفر',
    operationDetails: 'تفاصيل العمليات', operationDetailsHint: 'يعرض من نفّذ كل بيع أو إرجاع أو إلغاء، مع الوقت والموقع والمحطة والمناوبة.', detailsLimited: 'يعرض جدول التفاصيل أحدث {limit} عملية كحد أقصى؛ الملخصات أعلاه تشمل كامل الفترة.', employeeFilter: 'الموظف', locationFilter: 'الموقع', stationFilter: 'المحطة', typeFilter: 'نوع العملية', allEmployees: 'كل الموظفين', allLocations: 'كل المواقع', allStations: 'كل المحطات', allTypes: 'كل العمليات',
    employee: 'الموظف', station: 'المحطة', shift: 'المناوبة', operationType: 'العملية', saleReference: 'مرجع البيع', dateTime: 'التاريخ والوقت', amount: 'المبلغ', noDetails: 'لا توجد عمليات تطابق عوامل التصفية.', operationCountUnit: 'عملية', formerEmployee: 'موظف سابق', formerStation: 'محطة سابقة', formerLocation: 'موقع غير منسوب',
  },
  ku: {
    title: 'ڕاپۆرتی ناوەندی کاشێر', subtitle: 'فرۆشتن و گەڕاندنەوە و هەڵوەشاندنەوە بەپێی شوێن و کارمەند و وێستگە لە تۆماری ناوەندی متمانەپێکراو.', back: 'بەڕێوەبردنی کاشێر',
    today: 'ئەمڕۆ', seven: '7 ڕۆژ', thirty: '30 ڕۆژ', all: 'هەموو', loading: 'ڕاپۆرتی ناوەندی ئامادە دەکرێت...', failed: 'بارکردنی ڕاپۆرتی ناوەندی کاشێر سەرکەوتوو نەبوو.', empty: 'لەو ماوەیەدا هیچ کرداری کاشێر نییە.',
    netSales: 'فرۆشتنی خاوێن', profit: 'قازانجی گشتی', operations: 'مامەڵەکانی فرۆشتن', units: 'دانەی فرۆشراوی خاوێن', refunds: 'بەهای گەڕاندنەوە و هەڵوەشاندنەوە', average: 'تێکڕای بەهای مامەڵەی فرۆشتن', voided: 'کرداری هەڵوەشاندنەوە', returns: 'کرداری گەڕاندنەوە',
    partialProfit: 'قازانجی پیشاندراو بەشێکییە چونکە تێچووی هەندێک دانە تۆمار نەکراوە.', partialProfitShort: 'قازانجی بەشەکی', unavailableProfit: 'زانیاری قازانج بۆ ئەم مەودایە بەردەست نییە. فەوری تێچوو بە سفر دانانێت.', historicalActivityNote: 'وردەکاری جێبەجێکردن بۆ {available} لە کۆی {total} کردار بەردەستە. هەندێک کرداری مێژوویی پێش تۆماری بەستنەوەی کارمەند و شوێن و وێستگە بوون، بۆیە لە ژمارە داراییەکاندا دەمێننەوە بەبێ دروستکردنی زانیاری نەبوو.', topProducts: 'زۆرترین فرۆشراو', topProfitable: 'زۆرترین قازانج', noTop: 'لەو ماوەیەدا هیچ بەرهەمێک بە فرۆشتنی خاوێنی پۆزەتیڤ نییە.', noProfitable: 'هیچ بەرهەمێک نییە کە بتوانرێت قازانجەکەی بە دڵنیایی ڕیزبەندی بکرێت؛ تێچووی ونبوو بە سفر دانانرێت.', revenueChart: 'هێڵکاری فرۆشتن بەپێی بەرهەم', unitsChart: 'دانە فرۆشراوەکان بەپێی بەرهەم', profitChart: 'هێڵکاری قازانج بەپێی بەرهەم',
    salesByStaff: 'کاریگەری دارایی بەپێی کارمەندی فرۆشیار', salesByStation: 'کاریگەری دارایی بەپێی وێستگەی فرۆشتن', salesByLocation: 'کاریگەری دارایی بەپێی شوێن', activityByStaff: 'کردارە جێبەجێکراوەکان بەپێی کارمەند', activityByStation: 'کردارە جێبەجێکراوەکان بەپێی وێستگە', activityByLocation: 'کردارە جێبەجێکراوەکان بەپێی شوێن', noGroupSales: 'لەو ماوەیەدا کاریگەری دارایی نییە.',
    sales: 'فرۆشتن', saleOps: 'فرۆشتن', returnOps: 'گەڕاندنەوە', voidOps: 'هەڵوەشاندنەوە', totalOps: 'کۆی گشتی', location: 'شوێن', currency: 'دراو', period: 'ماوە', profitStatus: 'دۆخی قازانج', metric: 'پێوەر', value: 'بەها', generated: 'دوایین نوێکردنەوە', source: 'سەرچاوە: تۆماری ناوەندی متمانەپێکراوی کاشێر لە سێرڤەر',
    operationDetails: 'وردەکاری کردارەکان', operationDetailsHint: 'کارمەند و کات و شوێن و وێستگە و مناوبەی هەر فرۆشتن و گەڕاندنەوە و هەڵوەشاندنەوە پیشان دەدات.', detailsLimited: 'خشتەی وردەکاری تەنها نوێترین {limit} کردار پیشان دەدات؛ کورتەکانی سەرەوە هەموو ماوەکە دەگرنەوە.', employeeFilter: 'کارمەند', locationFilter: 'شوێن', stationFilter: 'وێستگە', typeFilter: 'جۆری کردار', allEmployees: 'هەموو کارمەندان', allLocations: 'هەموو شوێنەکان', allStations: 'هەموو وێستگەکان', allTypes: 'هەموو کردارەکان',
    employee: 'کارمەند', station: 'وێستگە', shift: 'مناوبە', operationType: 'کردار', saleReference: 'ژمارەی فرۆشتن', dateTime: 'بەروار و کات', amount: 'بڕ', noDetails: 'هیچ کردارێک لەگەڵ پاڵێوەرەکان ناگونجێت.', operationCountUnit: 'کردار', formerEmployee: 'کارمەندی پێشوو', formerStation: 'وێستگەی پێشوو', formerLocation: 'شوێنی دیارینەکراو',
  },
  en: {
    title: 'Central Cashier Report', subtitle: 'Sales, returns and voids by location, employee and station from the trusted central record.', back: 'Cashier management',
    today: 'Today', seven: '7 days', thirty: '30 days', all: 'All', loading: 'Building central cashier report...', failed: 'Could not load the central cashier report.', empty: 'No cashier operations in this period.',
    netSales: 'Net sales', profit: 'Gross profit', operations: 'Sales operations', units: 'Net units sold', refunds: 'Returns & voids value', average: 'Average sale ticket', voided: 'Void operations', returns: 'Return operations',
    partialProfit: 'Shown profit is partial because cost is missing for some units.', partialProfitShort: 'Partial profit', unavailableProfit: 'Profit data is unavailable for this scope. Fawri does not assume missing cost is zero.', historicalActivityNote: 'Execution details are available for {available} of {total} operations. Some historical operations predate employee, location and station attribution, so they remain in the financial totals without inventing missing attribution.', topProducts: 'Top-selling products', topProfitable: 'Most profitable products', noTop: 'No products have positive net sales in this period.', noProfitable: 'No products can be ranked by profit truthfully in this period; missing cost is never treated as zero.', revenueChart: 'Product sales chart', unitsChart: 'Units sold by product', profitChart: 'Product profit chart',
    salesByStaff: 'Financial impact by employee', salesByStation: 'Financial impact by station', salesByLocation: 'Financial impact by location', activityByStaff: 'Executed operations by employee', activityByStation: 'Executed operations by station', activityByLocation: 'Executed operations by location', noGroupSales: 'No financial impact in this period.',
    sales: 'sales', saleOps: 'Sales', returnOps: 'Returns', voidOps: 'Voids', totalOps: 'Total', location: 'Location', currency: 'Currency', period: 'Period', profitStatus: 'Profit status', metric: 'Metric', value: 'Value', generated: 'Last updated', source: 'Source: trusted central cashier record on the server',
    operationDetails: 'Operation details', operationDetailsHint: 'Shows who executed each sale, return or void together with its time, location, station and shift.', detailsLimited: 'The detail table shows at most the latest {limit} operations; the summaries above cover the full period.', employeeFilter: 'Employee', locationFilter: 'Location', stationFilter: 'Station', typeFilter: 'Operation type', allEmployees: 'All employees', allLocations: 'All locations', allStations: 'All stations', allTypes: 'All operations',
    employee: 'Employee', station: 'Station', shift: 'Shift', operationType: 'Operation', saleReference: 'Sale reference', dateTime: 'Date & time', amount: 'Amount', noDetails: 'No operations match these filters.', operationCountUnit: 'operations', formerEmployee: 'Former employee', formerStation: 'Former station', formerLocation: 'Unattributed location',
  },
};
