from pathlib import Path

path = Path('artifacts/api-server/src/routes/index.ts')
text = path.read_text(encoding='utf-8')

replacements = [
('''import {\n  connectMetaChannel,\n  readMetaChannelCredential,\n} from "../services/metaChannelRuntime";\n''', '''import {\n  connectMetaChannel,\n  readMetaChannelCredential,\n} from "../services/metaChannelRuntime";\nimport {\n  connectMetaChannelAuthoritative,\n  listMetaChannelsAuthoritative,\n} from "../services/postgresMetaChannelAuthority";\nimport {\n  getMerchantOperationalDecisionAuthoritative,\n} from "../services/merchantOperationalAccess";\nimport { operationalPostgresAuthorityRequired } from "../services/operationalPostgresAuthority";\n'''),
('''function loadRuntimeDb() {\n  try {\n''', '''function loadRuntimeDb() {\n  if (operationalPostgresAuthorityRequired()) return;\n  try {\n'''),
('''function saveRuntimeDb() {\n  try {\n''', '''function saveRuntimeDb() {\n  if (operationalPostgresAuthorityRequired()) return;\n  try {\n'''),
('''function readBotProductsForHttp(\n  res: Response,\n  merchantId: string,\n): Product[] | null {\n  try {\n''', '''function readBotProductsForHttp(\n  res: Response,\n  merchantId: string,\n): Product[] | null {\n  if (operationalPostgresAuthorityRequired()) {\n    res.setHeader("Cache-Control", "no-store");\n    res.status(410).json({\n      ok: false,\n      merchant_id: merchantId,\n      code: "LEGACY_RUNTIME_AUTHORITY_DISABLED",\n      error: "legacy bot runtime is disabled; use the PostgreSQL operational APIs",\n    });\n    return null;\n  }\n  try {\n'''),
('''export function saveMessengerConversation(params: {\n''', '''export function saveMessengerConversation(params: {\n'''),
('''}) {\n  const current = conversationsByMerchant.get(params.merchantId) || [];\n  const conversationId = `messenger-${params.customerId}`;\n''', '''}) {\n  if (operationalPostgresAuthorityRequired()) {\n    throw Object.assign(new Error("legacy Messenger conversation persistence is disabled"), {\n      code: "LEGACY_RUNTIME_AUTHORITY_DISABLED",\n    });\n  }\n  const current = conversationsByMerchant.get(params.merchantId) || [];\n  const conversationId = `messenger-${params.customerId}`;\n'''),
('''router.get("/bot/conversations/:merchantId", requireMerchantSession, (req: Request, res: Response) => {\n  const merchantId = getMerchantIdFromSession(res);\n''', '''router.get("/bot/conversations/:merchantId", requireMerchantSession, (req: Request, res: Response) => {\n  const merchantId = getMerchantIdFromSession(res);\n  if (operationalPostgresAuthorityRequired()) {\n    return res.status(410).json({ ok: false, code: "LEGACY_RUNTIME_AUTHORITY_DISABLED", error: "legacy bot conversation runtime is disabled" });\n  }\n'''),
('''router.get("/bot/orders/:merchantId", requireMerchantSession, (req: Request, res: Response) => {\n  const merchantId = getMerchantIdFromSession(res);\n''', '''router.get("/bot/orders/:merchantId", requireMerchantSession, (req: Request, res: Response) => {\n  const merchantId = getMerchantIdFromSession(res);\n  if (operationalPostgresAuthorityRequired()) {\n    return res.status(410).json({ ok: false, code: "LEGACY_RUNTIME_AUTHORITY_DISABLED", error: "legacy bot order runtime is disabled" });\n  }\n'''),
('''router.get("/meta/pages", requireMerchantSession, (_req: Request, res: Response) => {\n  const merchantId = getMerchantIdFromSession(res);\n  const pages = Array.from(metaPagesByPageId.values())\n    .filter((page) => page.merchant_id === merchantId)\n    .map((page) => ({\n      page_id: page.page_id,\n      page_name: page.page_name,\n      platform: page.platform,\n      connected_at: page.connected_at,\n    }));\n  return res.json({ ok: true, merchant_id: merchantId, pages });\n});\n''', '''router.get("/meta/pages", requireMerchantSession, async (_req: Request, res: Response) => {\n  const merchantId = getMerchantIdFromSession(res);\n  if (operationalPostgresAuthorityRequired()) {\n    const channels = await listMetaChannelsAuthoritative(merchantId);\n    const pages = channels\n      .filter((channel) => channel.page_id)\n      .map((channel) => ({\n        page_id: channel.page_id,\n        page_name: channel.page_name,\n        platform: channel.platform,\n        connected_at: channel.connected_at,\n      }));\n    return res.json({ ok: true, merchant_id: merchantId, pages });\n  }\n  const pages = Array.from(metaPagesByPageId.values())\n    .filter((page) => page.merchant_id === merchantId)\n    .map((page) => ({\n      page_id: page.page_id,\n      page_name: page.page_name,\n      platform: page.platform,\n      connected_at: page.connected_at,\n    }));\n  return res.json({ ok: true, merchant_id: merchantId, pages });\n});\n'''),
('''router.post("/meta/webhook", async (req: Request, res: Response) => {\n  try {\n''', '''router.post("/meta/webhook", async (req: Request, res: Response) => {\n  if (operationalPostgresAuthorityRequired()) {\n    res.setHeader("Cache-Control", "no-store");\n    return res.status(410).json({\n      ok: false,\n      code: "LEGACY_META_WEBHOOK_DISABLED",\n      error: "legacy Meta webhook runtime is disabled",\n    });\n  }\n  try {\n'''),
('''  if (!merchantSessionAccountExists(state.merchantId)) {\n    return res.status(401).send("Merchant account is unavailable");\n  }\n\n  const merchantId = state.merchantId;\n''', '''  if (operationalPostgresAuthorityRequired()) {\n    const decision = await getMerchantOperationalDecisionAuthoritative(state.merchantId);\n    if (!decision.allowed) {\n      return res.status(decision.statusCode).send("Merchant account is unavailable");\n    }\n  } else if (!merchantSessionAccountExists(state.merchantId)) {\n    return res.status(401).send("Merchant account is unavailable");\n  }\n\n  const merchantId = state.merchantId;\n'''),
('''      connectMetaChannel({\n        merchantId,\n        platform: connection.platform,\n        pageId: connection.page_id,\n        pageName: connection.page_name,\n        accessToken: pageAccessToken,\n        webhookSubscribed: connection.webhook_subscribed,\n        instagramAccountId: connection.instagram_account_id,\n        instagramUsername: connection.instagram_username,\n      });\n\n      connectedPages.push(connection);\n      metaPagesByPageId.set(connection.page_id, connection);\n    }\n\n    saveRuntimeDb();\n''', '''      await connectMetaChannelAuthoritative({\n        merchantId,\n        platform: connection.platform,\n        pageId: connection.page_id,\n        pageName: connection.page_name,\n        accessToken: pageAccessToken,\n        webhookSubscribed: connection.webhook_subscribed,\n        instagramAccountId: connection.instagram_account_id,\n        instagramUsername: connection.instagram_username,\n      });\n\n      connectedPages.push(connection);\n      if (!operationalPostgresAuthorityRequired()) {\n        metaPagesByPageId.set(connection.page_id, connection);\n      }\n    }\n\n    if (!operationalPostgresAuthorityRequired()) saveRuntimeDb();\n'''),
]

for old, new in replacements:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'expected legacy-router target exactly once, found {count}: {old[:100]!r}')
    text = text.replace(old, new, 1)

path.write_text(text, encoding='utf-8')
